/** Centralized client-side route paths. All components should use these instead of hardcoding paths. */
export const AppRoutes = {
  home: () => '/',
  login: () => '/login',
  setup: () => '/setup',

  // Viewer
  catalog: () => '/catalog',
  title: (titleId: number) => `/title/${titleId}`,
  actor: (personId: number) => `/actor/${personId}`,
  search: (query?: string) => query ? `/search?q=${encodeURIComponent(query)}` : '/search',
  movies: () => '/content/movies',
  tvShows: () => '/content/tv',
  collections: () => '/content/collections',
  collection: (collectionId: number) => `/content/collection/${collectionId}`,
  tags: () => '/content/tags',
  tag: (tagId: number) => `/tag/${tagId}`,
  personalVideos: () => '/content/family',
  wishlist: () => '/wishlist',
  cameras: () => '/cameras',
  liveTv: () => '/live-tv',
  play: (transcodeId: number) => `/play/${transcodeId}`,
  profile: () => '/profile',
  help: () => '/help',

  // Admin
  adminAdd: () => '/admin/add',
  adminTranscodeStatus: () => '/admin/transcodes/status',
  adminTranscodeUnmatched: () => '/admin/transcodes/unmatched',
  adminTranscodeLinked: () => '/admin/transcodes/linked',
  adminTranscodeBacklog: () => '/admin/transcodes/backlog',
  adminUsers: () => '/admin/users',
  adminSettings: () => '/admin/settings',
  adminValuation: () => '/admin/valuation',
  adminPurchaseWishes: () => '/admin/purchase-wishes',
  adminDataQuality: () => '/admin/data-quality',
  adminInventory: () => '/admin/inventory',
  adminCameras: () => '/admin/cameras',
  adminLiveTv: () => '/admin/live-tv',
  adminTags: () => '/admin/tags',
  adminImport: () => '/admin/import',
  adminExpand: () => '/admin/expand',
  adminFamilyMembers: () => '/admin/family-members',
  adminDocumentOwnership: () => '/admin/document-ownership',
  adminMediaItem: (itemId: number) => `/admin/item/${itemId}`,
} as const;
